name: redstone_database_mongo
description: MongoDB extension for redstone_database_plugin
version: 0.5.0
authors:
  - Stéphane Este-Gracias <sestegra@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/dartsome/redstone_database_mongo

environment:
  sdk: '>=2.0.0-dev.67.0 <2.0.0'

dependencies:
  connection_pool:
    git:
      url: https://github.com/dartsome/connection_pool.git
      ref: d9387ca9c46db6033121b7536405a033a5250fac
  mongo_dart: ^0.3.2
  redstone_database_plugin: ^0.4.0
  redstone:
    git:
      url: https://github.com/dartsome/redstone.git
      ref: bcba82b4a4a7bf290577e7eb07f5a33ae671e2de

dev_dependencies:
  serializer_generator: ^0.8.0
  test: ^1.2.0

#dependency_overrides:
#  connection_pool:
#    path: ../connection_pool_2