name: redstone_database_mongo
description: MongoDB extension for redstone_database_plugin
version: 0.1.1
authors:
  - Stéphane Este-Gracias <sestegra@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/dartsome/redstone_database_mongo

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  connection_pool: ^0.1.1
  mongo_dart: ^0.2.9
  redstone: ^0.6.7
  redstone_database_plugin: ^0.1.0+1
  serializer: ^0.4.0

dev_dependencies:
  test: ^0.12.0
